INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (1, 'BINV1010-1', 'Algorithmique', 1, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (2, 'BINV1020-1', 'Analyse et programmation orientée objet', 1, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (3, 'BINV1030-1', 'Gestion de données: bases', 1, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (4, 'BINV1040-1', 'Structures de données: bases', 1, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (5, 'BINV1050-1', 'Développement Web: bases', 1, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (6, 'BINV1060-1', 'OS', 1, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (7, 'BINV1070-1', 'Fonctionnement des ordinateurs', 1, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (8, 'BINV1080-2', 'Eco', 1, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (9, 'BINV1090-1', 'Mathématiques', 1, 4, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (10, 'BINV1100-1', 'Mathématiques 2', 1, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (11, 'BINV1110-1', 'Projet Web 1', 1, 3, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (12, 'BINV1120-1', 'Anglais', 1, 4, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (13, 'BINV2011-1', 'Langage C', 2, 3, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (14, 'BINV2160-1', 'Analayse et modélisation', 2, 4, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (15, 'BINV2040-1', 'Gestion des données: Avancé', 2, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (16, 'BINV2130-1', 'Programmation Java: Avancé', 2, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (17, 'BINV2150-2', 'Développement Web: Avancé', 2, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (18, 'BINV2190-1', 'DevOps', 2, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (19, 'BINV2140-1', 'Structure de données: Avancé', 2, 3, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (20, 'BINV2080-1', 'Organisation des entreprises', 2, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (21, 'BINV2090-2', 'Conception d''application d''entreprise', 2, 8, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (22, 'BINV2181-2', 'Linux: Programmation distribuée', 2, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (23, 'BINV2110-2', 'Informatique mobile', 2, 3, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (24, 'BINV2120-1', 'Anglais 2', 2, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (25, 'BINV3011-1', 'Langage C Avancé', 3, 3, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (27, 'BINV3160-1', 'Analyse et modélisation: Avancé', 3, 4, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (28, 'BINV3040-1', 'Gestion de données: Avancé++', 3, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (29, 'BINV3130-1', 'Programmation Java: Avancé++', 3, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (30, 'BINV3150-2', 'Web: Avancé++', 3, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (31, 'BINV3190-1', 'DevOps: Avancé', 3, 5, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (32, 'BINV3140-1', 'SD: Avancé++', 3, 3, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (33, 'BINV3080-1', 'Organisation des entreprises: avancé', 3, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (34, 'BINV3090-2', 'SQP', 3, 8, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (35, 'BINV3181-2', 'Linux Avancé++', 3, 6, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (36, 'BINV3110-2', 'Informatique mobile ++', 3, 3, 0);
INSERT INTO project_sql.ues (id_ue, code_ue, nom, bloc, nombre_de_credits, nombre_d_inscrits) VALUES (37, 'BINV3120-1', 'Anglais 3', 3, 5, 0);
